commit_message: "[TRANSLATION] Update %language% translation from Crowdin"
append_commit_message: false

files:
  - source: /bundles/bundle.properties
    translation: /bundles/bundle_%locale%.properties
